[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "16"

[build]
  publish = "docs/.vuepress/dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store --registry=https://registry.npmmirror.com && npx pnpm run build"
